### ISSUE TITLE
'SD_DETECT_PIN' was not declared in this scope

### ISSUE THREAD

**Issue by Seelenkind** [FYSETC/FYSETC-USB-Host-Adapter#1]
How to solve this problem ? 
Board BTT SKR Mini E3 V2.0 
Marlin 2.0.7.2

![image](https://user-images.githubusercontent.com/75549196/106912690-8a6e9d80-6703-11eb-8371-4f6d4f87beba.png)

**Comment by GerogeFu** [comment]
This board should have SD_DETECT pin as decribe in pins file
![image](https://user-images.githubusercontent.com/7496375/108581720-3b16a700-736a-11eb-802a-bc81c77be976.png)
